### ISSUE TITLE
Refinement and Planning Sessions

### ISSUE THREAD

**Issue by schwesig** [open-services-group/community#117]
Refinement and Planning Sessions

started in discussion gchat
Thoth Station Developer Chat
by @goern Mon, Apr 4, 5:20am

we have just a tiny discussion about how we want to drive forward the refinement/planning sessions, and I would like everyone's input on that:
1. we want to have a workflow that enables SIGs to refine and plan features, these should be in line with our MVP and Open Services Group's OKRs. planned features should work well with the sprint goals noted down on the current release issue
2. we want to turn the team/community wide refinement and planning sessions into an informational session: everybody should be brought up to speed of whats happening in sigs, what the planning status is and where issues to be debated have surfaced. Debating the issue could be done during the meeting, ... or offline
3. I'll propose an assignment of repos to SIGS, this seems to be an open issues
4. assigning issues to sigs (during issue triage) is based on semantics of the issue, and could happen a little but fuzzy. more important: sig leads should quickly review issues and split/reassign them if the issue feels wrong-placed in a sig

**Comment by goern** [comment]
for Thoth Station we have https://github.com/thoth-station/core/blob/master/docs/TermsAndConditionsForTheScrum.md which guides us what the outcome of a refinement session shall be

**Comment by codificat** [comment]
> for Thoth Station we have https://github.com/thoth-station/core/blob/master/docs/TermsAndConditionsForTheScrum.md which guides us what the outcome of a refinement session shall be

Is this enough or is there anything else needed here?
