### ISSUE TITLE
[Xpt] I, as a (first time) visitor of op1st, want to have a more modern theme/look&feel of the op1st landing page operaste-first.cloud, so I do feel like being on an interesting and up-to-date website, that represents the edge technology that it is selling.

### ISSUE THREAD

**Issue by schwesig** [open-services-group/community#133]
Persona/ User: (First time) visitor of op1st
User's Story: I want to have a more modern theme/look&feel of the op1st landing page operate-first.cloud
Reason: so I do feel like being on an interesting and up-to-date website, that represents the edge technology that it is selling.

Define Done:
1 to 3 first sprint
1. [small] Having 3 templates to present to the stakeholder (paid or free) e.g. https://themeforest.net/
everybody finds 3 templates, on Thursday in the daily Scrum
2. [small] presenting it to Marcel/Stakeholder
3. [?] Presenting it to the WG Website Update and find an agreement (net time small, gros time medium/large)
4. [medium] deploy it, customize, maybe change links, maybe special knowledge (either we can do it in medium, or find somebody who can do it in medium time)

## Additional Info:
e.g. MoSCoW
MUST
https://www.gatsbyjs.com/ compatible theme
found templates go into the comment area below

#### affected by:
- https://github.com/orgs/operate-first/projects/48

#### will affect:
- https://www.operate-first.cloud/
- https://github.com/orgs/operate-first/projects/48

**Comment by schwesig** [comment]
important note:
needs to be under oss licence
start here
https://www.gatsbyjs.com/starters/

**Comment by schwesig** [comment]
STOP working on this topic:
related to a discussion in the WG Website Update:
There will be a website (operate-first.cloud) theme and a blog theme.
We weren't able to find an OSS template that has most of the needed action elements and block elements to fit our needs, therefore we stay with the old theme for now.
The blog theme can be more freely selected, the needed elements and blocks are available in some of the OSS templates.
This topic is with @durandom right now.

**Comment by durandom** [comment]
I think this can be closed since we've upgraded the website to a new theme
