### ISSUE TITLE
As a Thoth Service owner I want to define a list of metrics to track

### ISSUE THREAD

**Issue by oindrillac** [open-services-group/community#141]
As a Thoth Service owner/maintainer, I want to see metrics related to the Thoth Guidance Service to track the quality of service offered and have a high level overview of the interactions with the community, so that we can funnel observations from these metrics back into operating the service.

- [x] Come up with aggregated metrics from the ones that are being captured in https://github.com/thoth-station/mi/issues/560, to offer high level overview of the service and see how close we are to meeting our [support requirements](https://docs.google.com/document/d/1xRglWo_NKlziwvVAiSLZw89YwOpUokmnkq-Ah4gdBJY/edit#).
- [x] Identify sources from where we would be collecting these metrics and determine how we want to aggregate and display these metrics.

**Comment by xtuchyna** [comment]
Updated issue for kebechet metrics:
- [ ] https://github.com/thoth-station/mi/issues/560

**Comment by oindrillac** [comment]
Started this initial [document](https://docs.google.com/document/d/1LSwAfFYx_oQ6gFCdW4oTZZuOt5PKFUAV7ib6l1fzFp0/edit?usp=sharing) with a list of metrics that can offer a high level overview of the service and its community. Feel free to add your suggestions.
