### ISSUE TITLE
[2pt] As a Thoth Service owner I want to have a list of criteria that constitute an issue so that I can measure when an issue is has enough information

### ISSUE THREAD

**Issue by Gkrumbach07** [open-services-group/community#143]
## Persona / User

Thoth Guidance Service owner

## User's Story

I want to have a list of criteria that constitutes an issue

## Reason

so that I can measure when an issue is has enough information

## Define Done

- [ ] A PR updating Thoth T&C with a new **issue quality** section

## Additional Info
Current [terms and conditions](https://github.com/thoth-station/core/blob/master/docs/TermsAndConditionsForTheScrum.md)

**Comment by Gkrumbach07** [comment]
Currently Thoth uses these labels to describe an issue:

- kind/bug - Categorizes issue or PR as related to a bug.
- kind/cleanup - Categorizes issue or PR as related to cleaning up code, process, or technical debt.
- kind/demo - This is an Issue or PR someone want to give a demo or request a demo.
- kind/deprecation - Categorizes issue or PR as related to a feature/enhancement marked for deprecation.
- kind/documentation - Categorizes issue or PR as related to documentation.
- kind/feature - Categorizes issue or PR as related to a new feature.
- kind/question - Categorizes issue or PR as a support question

I was thinking that each support question could be categorized into feature, question, or bug

**Comment by suppathak** [comment]
Yup, It does makes sense.

Also, It seemed to me that this particular issue is similar to #145 . Wdyt? Are there any difference between the two?

**Comment by Gkrumbach07** [comment]
I would argue that issue #145 comes after this issue. This issues deliverables is just criteria for what makes an issue, where as #145 is about creating/altering specific templates.

**Comment by Gkrumbach07** [comment]
Changed acceptance criteria to accept Pep's PR as a definition of done.

/assign @codificat 
/unassign @suppathak 
/unassign @Gkrumbach07
