### ISSUE TITLE
As a Thoth Guidance Service user, I want to have a clear understanding on which channel(s) of communication I should use so that I get assistance faster

### ISSUE THREAD

**Issue by Gkrumbach07** [open-services-group/community#148]
## Persona / User

Thoth Guidance Service user

## User's Story

I want to have a clear understanding on which channel(s) of communication I should use

## Reason

so that I get assistance faster

## Define Done

- [ ] Decide if to use a chat channel
- [ ] Decide on having one or multiple communication channels
- [ ] Decide the role of each communication channel

## Additional Info
Current known community channels: GitHub issues, Slack, G-Chat

**Comment by Gkrumbach07** [comment]
## Decisions

### Decide if to use a chat channel
**Pros**
- quicker back and forth communication

**Cons**
- some channels dont store a full history of conversations
- have to convert threads into text on a GitHub issue for tracking
- not metric consuming friendly

**Decision**
- [ ] Yes
- [ ] No

### Decide on having one communication channel (GitHub)
**Pros**
- everything is archived in one place
- no need to sync conversations across channels
- no confusion on what channel is preferred

**Cons**
- limits the ways to communicate effectively
- alienates people that are not comfortable with GitHub issues

**Decision**
- [ ] Yes
- [ ] No


### Decide the role of each communication channel (If using more than one)
**GitHub Issues**

**Slack**

**G-Chat**

**Comment by Gkrumbach07** [comment]
**Decide if to use a chat channel** [_Yes  G-Chat_]
Chat adds values to a community, but I wouldn't want it to be the primary form of communication due to the extra steps needs for archives and metrics. I vote to use G-chat as it supports threads and is already used by Thoth.

**Decide on having one communication channel (GitHub)**[ _Yes_]
Include a chat channel

**Decide the role of each communication channel (If using more than one)**

- GitHub Issues
Main form of conversation and problem tracking

- G-Chat
use a medium to formulate user stories from users and redirect them to new issues in github.

**Comment by oindrillac** [comment]
1. Are non-RH members able to join g-chat? (Are we de-prioritizing non-RH user persona initially)
2. Any existing bots that we can use to export chat threads into a github issue?

**Comment by suppathak** [comment]
1. GitHub issue : If a user wants a support which would require some technical help. 
2. Slack: If a user (Red Hat or non Red Hat) wants some minor help or has some questions about the service. Also, I guess in the slack itself, the user can be directed to open an issue in GitHub.
3. G-chat: I suppose it can be used on only RH members right? The I am not sure if this would be a good way for communication, mainly because the helpful conversations happening in g-chat cannot be seen by non-RH users. Unless, we are de-prioritizing on non-RH user persona initially.

**Comment by Gkrumbach07** [comment]
The [decision](https://github.com/open-services-group/community/issues/148#issuecomment-1104415073) is to use two communication channels: Slack for quick questions and minor help, and GitHub for hosting bigger issues that should be tracked.

**Comment by Gkrumbach07** [comment]
Accepted:  Slack may be preferred but if we want to reach more people we need more than one channel (i.e. have both slack and gchat). We decided on setting up a Slack instance/server, but not removing the old public facing gchat. We will monitor usage to see if slack is worth keeping or migrating too
