### ISSUE TITLE
[3pt][E1] As the owner/chair of the github op1st support I want to learn more about best ways how to use github, projects so my issues are easier to maintain, easier to understand by the community and different contributors, so everybody can see who is working on what in what time and status.

### ISSUE THREAD

**Issue by schwesig** [open-services-group/community#157]

**Comment by erikerlandson** [comment]
There are a few alternative approaches to this:
1. improve navigation from `community` page(s) so people from other adjacent communities can navigate to opf-specific boards.
2. cross-linking issues (e.g. from an issue filed on `os_c_data_commons` or other osc project to some corresponding issue on OPF)
3. Adding a link to an OPF issue into an OSC kanban "note": 
a. https://tosbourn.com/github-projects-different-organisations/ 
b. example: https://github.com/orgs/os-climate/projects/4#card-81398605
 
I think (3) probably most directly addresses the use case for any specific issue: it allows the external community (example OSC) to track particular activities they are interested in relating to tasks requiring OPF to execute.

Benefits:
- allows specific linking between tasks on one project/kanban to a specific corresponding task over on OPF
- similarly, allows external stakeholders direct visibility into any progress or status change
- Possible to navigate from your board, to OPF issue, to any associated OPF boards (requires two clicks)

Weaknesses:
- Someone with edit rights to the external project/kanban must acquire the link to corresponding OPF issue to establish the link.

Mitigations:
- establish a utility card once, with link to OPF board(s), for convenient reference?
- assign an OPF representative (e.g. Humair) to provide such a link, probably on an originating issue from external
- this linkage should be established at the point where an external need transitions to a specific request to OPF

**Comment by erikerlandson** [comment]
IMO the new "beta" github projects have nice options for project visualization, and for anyone who can navigate to OPF project board, it would improve ability to understand the state of OPF activities

Many people create boards without "beta", and it would be nice if "beta" became the default.

**Comment by erikerlandson** [comment]
Another issue with my proposed solution is that the most likely project board is private:
![image](https://user-images.githubusercontent.com/259898/166335964-a2588aa0-2ef7-4d43-b82d-82353b0f0bdc.png)

**Comment by erikerlandson** [comment]
I cannot close this but now that OPF and OSC have been properly advised, I view it as complete.
