### ISSUE TITLE
[3pt][E3] As a visitor of operate-first.cloud (ng), I want all the social media buttons on the website to work properly, so I have different options to communicate with the community and be informed.

### ISSUE THREAD

**Issue by schwesig** [open-services-group/community#163]
## Persona / User
visitor of operate-first.cloud

## User's Story
I want all the social media buttons on the website to work properly

## Reason
So I have different options to communicate with the community and be informed

## Define Done
1. github icon is linked to https://github.com/operate-first
2. slack icon is linked to https://operatefirst.slack.com/ssb/redirect
3. youtube icon is linked to https://www.youtube.com/channel/UCe87bwqlGoBQs2RvMQZ5_sg
4. twitter icon is linked to https://twitter.com/OperateFirst
5. github icon is linked to https://github.com/operate-first
6. slack icon is linked to https://operatefirst.slack.com/ssb/redirect

**Comment by schwesig** [comment]
6 social media buttons are on the page
![image.png](https://images.zenhubusercontent.com/618d63a33497546376904a9f/0c82aeb5-3740-4fbd-b7f0-fa19a3e0f5c1)

**Comment by aakankshaduggal** [comment]
Buttons 1,2,3,4 are addressed by this PR - https://github.com/operate-first/website-ng/pull/9

**Comment by aakankshaduggal** [comment]
Updated links for these buttons :
![image](https://user-images.githubusercontent.com/26301643/167207734-b3860587-5960-4a0d-af40-983aecfa0919.png)
in the PR - https://github.com/operate-first/website-ng/pull/11
