### ISSUE TITLE
[2pt][E3] As a visitor of operate-first.cloud (ng), I want the Community menu item to work, so I can find out about the community and participate.

### ISSUE THREAD

**Issue by schwesig** [open-services-group/community#165]

**Comment by schwesig** [comment]
https://www.operate-first.cloud/community/README.html

**Comment by schwesig** [comment]
![image.png](https://images.zenhubusercontent.com/618d63a33497546376904a9f/f9b43473-cd82-4bbd-a38a-8ac6dd92a6bc)

**Comment by hemajv** [comment]
@schwesig do we know where this should be redirected to?

**Comment by hemajv** [comment]
@bryanmontalvan has created a new landing pages for the `Community` tab: https://github.com/operate-first/website-ng/pull/12
You can view the landing page here: https://www.operate-first.cloud/website-ng/community
