### ISSUE TITLE
[2pt][E3] As a visitor of operate-first.cloud (ng), I want the Docs&Training menu item to work, so I can look up solutions and learn the basics and become better.

### ISSUE THREAD

**Issue by schwesig** [open-services-group/community#166]

**Comment by schwesig** [comment]
![image.png](https://images.zenhubusercontent.com/618d63a33497546376904a9f/7f325390-c8fb-4d36-9e92-5ff04a5625c0)

**Comment by schwesig** [comment]
consider this
https://hackmd.io/KE7KRZZRQwyQfRYZw78k_Q

copy below from version 2022-05-04 09:29 ET

1. Docs & Training [landing page]
    1. GitOps documention: https://www.operate-first.cloud/apps/content/README.html 
    2. Stephanie can add training links to the page when it's ready
    3. Layout
        - (Getting Started)
        - Docs
            - [Getting Started](/commmunity/getting-started/)
            - [User & Contributor Handbook](/community-handbook)
            - [Community Cloud Operations Documentation](/apps/content/)
            - [Data Science Workflow & Best Practices]()
        - Training
            - [Overview](/training)
            - ["Open Source Basics"](/training/open-source-basics)
            - ["Introduction to Operate First"](/training/introduction-to-operate-first)

**Comment by aakankshaduggal** [comment]
@schwesig it's unclear to me as to where do we redirect the docs&training button to?

**Comment by schwesig** [comment]
according to https://github.com/open-services-group/community/issues/151 and the miro board in there,
to Blueprints or/and (via a landing page, if available) to Data Science Learning Pathway
![image](https://user-images.githubusercontent.com/89909507/167145583-6ca645bf-1fe5-42b7-b006-2d61e8f7f945.png)

**Comment by hemajv** [comment]
@bryanmontalvan has created a new landing page for the `Docs/Training` tab: https://github.com/operate-first/website-ng/pull/12
You can view the landing page here: https://www.operate-first.cloud/website-ng/docs-training

We need to add some more content to this page
