### ISSUE TITLE
[2pt][E3] As a visitor of operate-first.cloud (ng), I want the Op1st Community Cloud menu item to work, so I can read more about the Operate First Environments Managed Services and more.

### ISSUE THREAD

**Issue by schwesig** [open-services-group/community#167]

**Comment by schwesig** [comment]
https://www.operate-first.cloud/apps/content/README.html

**Comment by hemajv** [comment]
@bryanmontalvan has created a new landing page for the `Op1st Community` tab: https://github.com/operate-first/website-ng/pull/12
You can view the landing page here: https://www.operate-first.cloud/website-ng/community-cloud

We still need to add some more content to this page
