### ISSUE TITLE
As a community member, I want to be able to interact with the community via a chat system

### ISSUE THREAD

**Issue by Gkrumbach07** [open-services-group/community#198]
## Persona
community member

## User Story
I want to be able to interact with the community via a chat system

## Done
- [ ] Create slack instance
- [ ] Add channels

**Comment by codificat** [comment]
See the https://www.operate-first.cloud website for pointers to existing [slack](https://join.slack.com/t/operatefirst/shared_invite/zt-o2gn4wn8-O39g7sthTAuPCvaCNRnLww).
/close
