### ISSUE TITLE
[8pt] As a Thoth service owner, I want to track Github metrics and display them on a dashboard and integrate them on the site.

### ISSUE THREAD

**Issue by oindrillac** [open-services-group/community#209]
As a part of https://github.com/open-services-group/community/issues/172, I want to track Github metrics and display them on a dashboard.

 - [ ] Extract relevant data and store them on S3. https://github.com/open-services-group/metrics/pull/38
 - [ ] Create notebooks to calculate metrics from the stored data.
 - [ ] Create charts from these metrics on a dashboard such as Superset or Grafana.
 - [ ] Integrate these dashboards on the Gatsby site.

**Comment by suppathak** [comment]
superset dashboard: http://superset.operate-first.cloud/r/12

**Comment by suppathak** [comment]
Dashboard integrated on Website: https://thoth-station.ninja/help/metrics/issue_metrics.md

**Comment by oindrillac** [comment]
@suppathak this is done correct? Can this be closed?

**Comment by suppathak** [comment]
> @suppathak this is done correct? Can this be closed?

I think it can be closed. Thanks :)

**Comment by schwesig** [comment]
/close
PRs merged
