### ISSUE TITLE
[1pt] As a Thoth service owner, I want to create a cron job (running every week) in order to track Github metrics displayed in thoth-station help page.

### ISSUE THREAD

**Issue by suppathak** [open-services-group/community#234]
As a Thoth service owner, I want to create a cron job (running every week) in order to track Github metrics displayed in thoth-station [help page](https://thoth-station.ninja/help/metrics/issue_metrics.md).

**Comment by suppathak** [comment]
Cron job created: https://console-openshift-console.apps.smaug.na.operate-first.cloud/k8s/ns/ds-ml-workflows-ws/cronjobs/thoth-support-metrics 

Every week, it runs and collect the github data from thoth-station/support repo which will then update the github metrics in thoth-station [help page](https://thoth-station.ninja/help/metrics/issue_metrics.md).

**Comment by codificat** [comment]
> Cron job created

so, this is complete
/close
