### ISSUE TITLE
Additional chair to SIG Services wanted!

### ISSUE THREAD

**Issue by tumido** [open-services-group/community#38]
any other volunteers?

_Originally posted by @durandom in https://github.com/open-services-group/community/pull/30#discussion_r791607184_

Hi team, I need a buddy to chair this SIG with me :slightly_smiling_face: . Please nominate anybody or volunteer below.

**Comment by Shreyanand** [comment]
Hey Tom, It'd be a great learning experience for me. Happy to co lead this SIG with you :)

**Comment by tumido** [comment]
Awesome! :+1: Yeah! Let's do it! :slightly_smiling_face:  Can you please send a PR and add yourself to
https://github.com/open-services-group/community/blob/245511c0abeca780747c903a1368a54091a5dd22/sigs.yaml#L64

(please run https://github.com/open-services-group/community/blob/245511c0abeca780747c903a1368a54091a5dd22/Containerfile#L16 after your edit)

**Comment by tumido** [comment]
Fixed via #52
