### ISSUE TITLE
[SIGComExp] Meet 2022-01 Notes

### ISSUE THREAD

**Issue by schwesig** [open-services-group/community#53]
2022-02-09
## Sources/Links
[Drawing Board](https://lucid.app/lucidspark/77c40968-dc6f-4d51-a1ab-02949cd8fe57/view?invitationId=inv_21afbe04-0815-4c26-a358-f17589129023#)
[Meeting Record](https://drive.google.com/file/d/1cdkFuZdeZlgoWBodUuJsxlsRmXrX71NF/view?usp=sharing)
[Continous Meeting Document](https://docs.google.com/document/d/1t47S9JUZbI3q0_LgVtaBKYsaGqnOP6YSG6x8XaBhiew/edit#)

#### Staffing
![2022-02-09 SIG Community Experience 1  2022 - Page 1 Staffing](https://user-images.githubusercontent.com/89909507/153359652-c6e2a0ae-7a75-407b-83bd-76af8680eb0c.png)

#### Status ToDos --> create Issues
![2022-02-09 SIG Community Experience 1  2022 - Page 1 Detail Planning](https://user-images.githubusercontent.com/89909507/153360151-7f7e9fd4-1963-436f-9a5a-ed4b2b03ce18.png)

**Comment by codificat** [comment]
Thanks @schwesig !

I updated [the meetings document](https://docs.google.com/document/d/1t47S9JUZbI3q0_LgVtaBKYsaGqnOP6YSG6x8XaBhiew/edit#) with the information.

Moving forward, the document will be referenced from the SIG's information documents (after #34 merges), so I believe we are all set here.

/close
