### ISSUE TITLE
[SIGComExp] Staffing Sub-Projects

### ISSUE THREAD

**Issue by schwesig** [open-services-group/community#56]
The three new Sub-Projects (SP) need to be staffed. The kick-off established the three SPs.
Lists of members and owners are not static or limited. Feel free to join.

**Comment by schwesig** [comment]
Our first official meeting yesterday (2022-02-09) filled some of the "open chairs":
https://github.com/open-services-group/community/issues/53
# SP Gov Org
- [ ] Owner: 
- [ ] Member/Contributor: @kpostlet 
- [ ] Member/Contributor: @tumido 

# SP ComCom
- [ ] Owner: 
- [ ] Member/Contributor: @kpostlet 
- [ ] Member/Contributor: @Ochatter
- [ ] Member/Contributor: @aakankshaduggal 
- [ ] Member/Contributor: @gkrumbac
- [ ] Member/Contributor: @mayaCostantini
- [ ] Member/Contributor: @suppathak
- [ ] Member/Contributor: @goern

# SP Metrics Strategic
- [ ] Owner:
- [ ] Member/Contributor: @goern
- [ ] Member/Contributor: @Ochatter
- [ ] Member/Contributor: @suppathak
- [ ] Member/Contributor: @aakankshaduggal 

# Others
- [ ] Check if "owner" is still the correct word. maintainer?

**Comment by chauhankaranraj** [comment]
> Lists of members and owners are not static or limited. Feel free to join.

I'm interested in joining the SP Metrics Strategic as well! :smiley:

**Comment by schwesig** [comment]
added @chauhankaranraj to the overview

**Comment by hemajv** [comment]
happy to contribute to the SP Metrics Strategic :smile:

**Comment by codificat** [comment]
As per recent SIG meetings, the decision was made to close the sub-projects and handle everything at the SIG level.
See #178 for more details.

Based on that, I believe that this issue is no longer relevant, so:
/close
