### ISSUE TITLE
Staff the SP ComCom, add to yaml

### ISSUE THREAD

**Issue by schwesig** [open-services-group/community#58]
- [ ]  Owner:
- [ ]  Member/Contributor: @kpostlet 
- [ ]  Member/Contributor: @Ochatter
- [ ]  Member/Contributor: @aakankshaduggal 
- [ ]  Member/Contributor: @gkrumbac
- [ ]  Member/Contributor: @mayaCostantini
- [ ]  Member/Contributor: @suppathak
- [ ]  Member/Contributor: @goern

**Comment by codificat** [comment]
As per recent SIG meetings, the decision was made to close the sub-projects and handle everything at the SIG level.
See #178 for more details.

Based on that, I believe that this issue is no longer relevant, so:
/close
