### ISSUE TITLE
Staff the SP GovOrg, add to yaml

### ISSUE THREAD

**Issue by schwesig** [open-services-group/community#59]
- [ ]  Owner:
- [ ]  Member/Contributor: @kpostlet 
- [ ]  Member/Contributor: @tumido

**Comment by schwesig** [comment]
https://github.com/thoth-station/core/blob/00f6ac50384b47f9cb1de3c8983d332631f6079c/docs/adr/template.md

**Comment by KPostOffice** [comment]
I like the labels 👍🏻

**Comment by codificat** [comment]
As per recent SIG meetings, the decision was made to close the sub-projects and handle everything at the SIG level.
See #178 for more details.

Based on that, I believe that this issue is no longer relevant, so:
/close
