### ISSUE TITLE
Staff the SP Metrics Strategic, add to yaml

### ISSUE THREAD

**Issue by schwesig** [open-services-group/community#61]
- [ ]  Owner:
- [ ]  Member/Contributor: @goern
- [ ]  Member/Contributor: @oindrillac 
- [ ]  Member/Contributor: @suppathak
- [ ]  Member/Contributor: @aakankshaduggal
- [ ]  Member/Contributor: @hemajv 
- [ ]  Member/Contributor: @chauhankaranraj

**Comment by hemajv** [comment]
happy to be a contributor to this sub-project! :)

**Comment by schwesig** [comment]
@hemajv happy to have you on board. I added you in the list

**Comment by chauhankaranraj** [comment]
I'd like to contribute as well! :)

**Comment by codificat** [comment]
As per recent SIG meetings, the decision was made to close the sub-projects and handle everything at the SIG level.
See #178 for more details.

Based on that, I believe that this issue is no longer relevant, so:
/close
