### ISSUE TITLE
[SP GovOrg] Promote ADRs e.g. where to store, where to publish, how to do, templates | collect new

### ISSUE THREAD

**Issue by schwesig** [open-services-group/community#69]
This issue is to track all open ADR related topics. maybe this should become an epic.
But main at the end, this is the task to promote and take care of the ADRs and the ADR process.
"long term coaching"

The comments below are for collecting informations or todos, that need to take care of in separate issues.

**Comment by schwesig** [comment]
- AICoE org on GitHub: has some repos that might/seem to belong to a certain subproject. All repos should belong to a subproject (in the OSG governance sense) and be actively worked on, if not: let’s put a note on the README and archive them. 
  - Each subproject (as it is part of a SIG) needs to support a Service being created by OSG 
  - We want owners for each repo, they are stated in the OWNERS file as an approver. Owners are accountable for maintaining code in the repository and the repository itself.
  - Each repo should be in one of three categories
    - none subproject, individual owned repo, purpose might be community building
    - subproject of a SIG
    - archived, and might be unarchived again…
  - Individual owned repositories might be repos OSG observes, as it is unclear if they support/contribute to a Services and should be promoted to a subproject.
- Creating a subproject should be medium hard, removing a subproject should be hard, as that modifies the ownership relationship.

**Comment by schwesig** [comment]
- [ ] All wg should have gdocs in readme

**Comment by schwesig** [comment]
https://github.com/open-services-group/community/pull/46

**Comment by schwesig** [comment]
https://github.com/thoth-station/core/blob/00f6ac50384b47f9cb1de3c8983d332631f6079c/docs/adr/template.md

**Comment by codificat** [comment]
@schwesig it is unclear to me what is pending to do about this issue, if anything.

There is a place for ADRs, and a template for them: https://github.com/open-services-group/community/tree/main/adr

I see some comments earlier that are about SIGs, WGs etc - but that sounds not directly related to ADRs, right?
