### ISSUE TITLE
[SIG ComExp] Overview of all Channels

### ISSUE THREAD

**Issue by schwesig** [open-services-group/community#76]
Show and Tell how we communicate,
list all ways and channels (gchat, slack, ...).
Maybe sorted/clustered by Groups or topics, if there are different ways.

Ideal solution: same channels for all SIGs and Groups....

SP ComCom or GovOrg

**Comment by oindrillac** [comment]
In general, I think we can think of two types or kinds of channels:

1. one to promote our content to a wider audience. eg: blogs, meetups, conferences, groups, websites etc which can also be tracked via https://github.com/open-services-group/community/issues/87 as separate issues similar to how we track conferences in https://github.com/orgs/AICoE/projects/5
2. one to share and communicate updates from meetings, decisions etc eg: gchat, email, slack, a webpage etc

I think there can be a few channels that might be overlapping, but i think its good to think of these 2 kinds of channels as distinct and serving slightly different purposes.

**Comment by schwesig** [comment]
/close
needs to be measured, partly is
not main focus of this SIG anymore
