### ISSUE TITLE
[SP ComCom] NewsFlash - Create a list of all Meetings in the [OSG] Calendar

### ISSUE THREAD

**Issue by schwesig** [open-services-group/community#85]
The NewsFlash project focuses first on the OSG Calendar (for Q1 and as a use case).
It also focuses first on output and establishing the process instead of automation first.
Later, the option of integrating more calendars and create an automated process will be checked.

This issue creates a list of all meetings in the Open Services Group Calendar.
This does not need to be an automated process, we need this list once to start. Fast before automation.
The OSG Calendar will also change, we take the current 

The needed fields are:

- Calendar (in this case only OSG)
- Meeting Title
- Date (Day)
- Time (no matter what timezone the meeting is set to, use Eastern Standard Time)
- Host/Chair (this maybe needs to be pulled from yaml file or else)

Why do we need these fields:

- Meeting Title to identify
- Date and Time for planning, when to send the pre- and after-meetings FlashNews
- Host/Chair to have a contact point for the notes and agenda content

**Comment by schwesig** [comment]
is someone taking care of this? We need this list to work on https://github.com/open-services-group/community/issues/89

**Comment by schwesig** [comment]
@kpostlet 
 @oindrillac
 @aakankshaduggal 
 @Gkrumbach07
 @mayaCostantini
 @suppathak
 @goern

**Comment by aakankshaduggal** [comment]
Initiated a doc here - https://docs.google.com/document/d/1eaue1WKZ8QygthWU-cKH1pwJxEcZbUvgTQ39-pT2bAw/edit?usp=sharing

cc - @schwesig

**Comment by schwesig** [comment]
/closed

List is good and can be used.
Thanks @aakankshaduggal 🤗

**Comment by schwesig** [comment]
| ID | current Meeting Title                                          | Host/Chair                                                                    | day       | time  | frequenzy | calendar |
|----|----------------------------------------------------------------|-------------------------------------------------------------------------------|-----------|-------|-----------|----------|
| 1  | [SIG-Data-Science] Metrics weekly meeting                      | Hema Veeradhi                                                                 | Monday    | 12:00 | weekly    | OSG      |
| 2  | SIG Stack Guidance Meeting                                     | Maya Costantini                                                               | Monday    | 9:00  | weekly    | OSG      |
| 3  | [OSG] Steering Committee                                       | Marcel Hild, Christoph Goern, Michael Clifford, Thorsten Schwesig, Tom Coufal | Tuesday   | 9:30  | weekly    | OSG      |
| 4  | DevSecOps WG                                                   | Humair Khan, Harshad Reddy Nalla                                              | Tuesday   | 11:00 | weekly    | OSG      |
| 5  | WG BYON Build Pipelines                                        | Francesco Murdaca, Oindrilla Chatterjee                                       | Wednesday | 10:00 | weekly    | OSG      |
| 6  | Community Experience SIG meeting                               | Thorsten Schwesig, Pep Turro Mauri                                            | Wednesday | 11:00 | bi-weekly | OSG      |
| 7  | [OSG] SIG-Data Science Meeting                                 | Michael Clifford                                                              | Wednesday | 11:00 | weekly    | OSG      |
| 8  | [SIG-Data Science] Operate First Data Science Community Meetup | Aakanksha Duggal                                                              | Wednesday | 12:00 | weekly    | OSG      |
| 9  | [WG-DevSecOps] Discuss Meeting                                 | Harshad Reddy Nalla                                                           | Wednesday | 12:30 | weekly    | OSG      |
| 10 | Seraph Talk                                                    | Tom Coufal                                                                    | Thursday  | 8:00  | weekly    | OSG      |
| 11 | [OSG] SIG Services                                             | Tom Coufal, Shrey Anand                                                       | Thursday  | 9:00  | bi-weekly | OSG      |
| 12 | [OSG] OS-Climate Meeting                                       | Erik Erlandson                                                                | Thursday  | 11:00 | weekly    | OSG      |
| 13 | Peribolos-as-a-service                                         | Tom Coufal, Michael Clifford                                                  | Thursday  | 9:00  | bi-weekly | OSG      |
