### ISSUE TITLE
remove sig/ and have sig-* on /

### ISSUE THREAD

**Issue by goern** [open-services-group/community#9]
... the example of the existing SIG dirs;
![image](https://user-images.githubusercontent.com/4494906/148814460-f251a2b3-a60b-4bdc-aaba-06ad6c0c422a.png)
should they all be modified to dash-case. 

Let's remove the "sig/" In the kubernetes example the sig directories are on the root of the project

_Originally posted by @MichaelClifford in https://github.com/open-services-group/community/pull/7#discussion_r781420039_

/kind feature
/priority important-soon
/assign schwesig

**Comment by schwesig** [comment]
https://github.com/goern/open-services-group-community/pull/2

**Comment by schwesig** [comment]
closed by PR https://github.com/open-services-group/community/pull/15
