### ISSUE TITLE
[SIG Data Science][SP Metrics] Add subproject repo urls to sigs.yaml

### ISSUE THREAD

**Issue by chauhankaranraj** [open-services-group/community#92]
As a part of the [Metrics](https://github.com/open-services-group/metrics) subproject, we want to collect the github data corresponding to all the subprojects under various sigs. For this, we need to have a list of repo's corresponding to each subproject. However, repo url's are not currently listed in sigs.yaml. Could we update it and add them?

Alternatively, we could also parse the repo slugs from the owners file entries in sigs.yaml. Here, however, we noticed that the urls are inconsistent across subprojects - for example see [this](https://github.com/open-services-group/community/blob/c37be8decb2297181d57bcdc4121eb94a1a9eb36/sigs.yaml#L92) and [this](https://github.com/open-services-group/community/blob/c37be8decb2297181d57bcdc4121eb94a1a9eb36/sigs.yaml#L96). Should we also update these to be uniform across the board?

/cc @hemajv @Shreyanand

**Comment by schwesig** [comment]
@Shreyanand thanks for cc, I will take care of this

/cc @codificat

**Comment by schwesig** [comment]
see @codificat link to #94, we not always have a specified repo for all groups.
kind of a catch 22 and we need maybe first a decision, if we first need to clean the "repo structure" or collecting the "connections" not fully and manually added?

**Comment by codificat** [comment]
I believe we should properly identify the repos and update `sigs.yaml` accordingly.

Besides that though, should we also consider SIGs in related projects (e.g. [Thoth](https://github.com/thoth-station/core/blob/master/community/sig-list.md)) or only the reference from this repo?

**Comment by schwesig** [comment]
> can't we just use the `OWNERS` link as a proxy?

what do you mean by "proxy" ?


> That would trickle down do all repos maintaining an `OWNERS` file too

and yes, that was in the plan. But I didn't want to wait on this to long and blocking the metrics, MVP.
