### ISSUE TITLE
Naming of all Meetings in the OSG Calendar

### ISSUE THREAD

**Issue by schwesig** [open-services-group/community#96]
Maybe thinking about a naming convention for Meetings?

Like [SIG name] Title ?
or [OSG][SIG name] Title

- [x] Let's discuss
- [ ] If yes, we need a naming convention, let's set it

Current Meetings in the OSG Calendar and their names
In scope: **OSG Google Calender**

| ID |current Meeting Title|Host/Chair|new Meeting Title|
|---|---|---|---|
| 1 | [SIG-Data-Science] Metrics weekly meeting | Hema Veeradhi |  [SIG Data Science] [SP Metrics] Meeting |
| 2 | SIG Stack Guidance Meeting | Maya Costantini | [SIG Stack Guidance] Meeting |
| 3 | [OSG] Steering Committee | Marcel Hild, Christoph Goern, Michael Clifford, Thorsten Schwesig, Tom Coufal | [SC OSG] Meeting|
| 4 | DevSecOps WG | Humair Khan, Harshad Reddy Nalla | [WG DevSecOps] Meeting |
| 5 | WG BYON Build Pipelines | Francesco Murdaca, Oindrilla Chatterjee | [WG BYON Build Pipelines] Meeting|
| 6 | Community Experience SIG meeting | Thorsten Schwesig, Pep Turro Mauri | [SG Community Experience] Meeting |
| 7 | [OSG] SIG-Data Science Meeting | Michael Clifford | [SIG Data Science] Meeting |
| 8 | [SIG-Data Science] Operate First Data Science Community Meetup | Aakanksha Duggal | [SIG Data Science] Operate First Data Science Community Meetup|
| 9 | [WG-DevSecOps] Discuss Meeting | Harshad Reddy Nalla | [WG DevSecOps] Discuss Meeting |
| 10 | Seraph Talk | Tom Coufal | [Seraph] Seraph Talk |
| 11 | [OSG] SIG Services | Tom Coufal, Shrey Anand | [SIG Services] Meeting |
| 12 | [OSG] OS-Climate Meeting | Erik Erlandson | [OS-Climate] Meeting |
| 13 | Peribolos-as-a-service | Tom Coufal, Michael Clifford | [Peribolos-as-a-service] Meeting |

**Comment by aakankshaduggal** [comment]
I totally agree that there should be a naming convention for all these meetings.
 My two cents here, since all these meetings are under the same org - OSG, we should not be mentioning that. Instead, we could do `[SIG]/[SIG - <name of SIG>][SP]/[WG] - Name of the meeting`, wdyt?

**Comment by schwesig** [comment]
> `[SIG]/[SIG - <name of SIG>][SP]/[WG] - Name of the meeting`, wdyt?

looks good to me
what do others think?
@codificat @tumido @goern @aakankshaduggal ...

**Comment by MichaelClifford** [comment]
+1

**Comment by codificat** [comment]
I agree, something like `(\[(SIG|WG) name\] )?meeting title` (some meetings don't belong to a SIG or WG)

**Comment by schwesig** [comment]
everybody feel free to comment or add the final name and how it should look like.
See table in the start comment https://github.com/open-services-group/community/issues/96#issue-1164323264

**Comment by oindrillac** [comment]
Some of the meeting titles have the words "weekly meeting", "bi-weekly meeting", "meeting" and some have nothing after `[sig/wg name][sp name]`. Shall we standardize this to keep either "meeting" or "cadence + meeting" or nothing after each meeting?
